apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patchesJson6902:
- target:
    group: template.openshift.io
    kind: Template
    version: v1
    name: assisted-events-stream-projection
  path: parameters.yaml
